name: dart_server
description: Aqueduct dictionery app.
version: 0.0.1
author: Majd Kazmoz

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0